### ISSUE TITLE
New release to PyPI

### ISSUE THREAD

**Issue by msabramo** [KushalP/serfclient-py#19]
It would be nice to have a new version on PyPI with recent additions like support for auth tokens and the `EnvironmentConfig` class (issue #16, PR #17).

**Comment by msabramo** [comment]
Latest version is https://pypi.python.org/pypi/serfclient/0.4.0 which was released in January.

**Comment by KushalP** [comment]
I've updated the changelog and tagged a new git release: https://github.com/KushalP/serfclient-py/releases/tag/v0.5.0

I need to head home to sign it and push it to PyPi.

**Comment by KushalP** [comment]
@msabramo v0.5.0 has been released: https://pypi.python.org/pypi/serfclient/0.5.0

Thanks for all of your contributions!
